.pragma library

// Generated by scripts/generate-theme-catalog.py. See third_party/tinted-schemes.
var themes = [
    {
        "id": "tinted-catppuccin-latte",
        "name": "Catppuccin Latte",
        "author": "https://github.com/catppuccin/catppuccin",
        "variant": "light",
        "background": "#eff1f5",
        "surface": "#e6e9ef",
        "text": "#4c4f69",
        "accent": "#8839ef",
        "good": "#40a02b"
    },
    {
        "id": "tinted-catppuccin-mocha",
        "name": "Catppuccin Mocha",
        "author": "https://github.com/catppuccin/catppuccin",
        "variant": "dark",
        "background": "#1e1e2e",
        "surface": "#181825",
        "text": "#cdd6f4",
        "accent": "#cba6f7",
        "good": "#a6e3a1"
    },
    {
        "id": "tinted-dracula",
        "name": "Dracula",
        "author": "clach04 (https://github.com/clach04)",
        "variant": "dark",
        "background": "#282a36",
        "surface": "#21222c",
        "text": "#f8f8f2",
        "accent": "#ff79c6",
        "good": "#50fa7b"
    },
    {
        "id": "tinted-gruvbox-dark-medium",
        "name": "Gruvbox dark, medium",
        "author": "Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)",
        "variant": "dark",
        "background": "#282828",
        "surface": "#3c3836",
        "text": "#d5c4a1",
        "accent": "#d3869b",
        "good": "#b8bb26"
    },
    {
        "id": "tinted-gruvbox-light-medium",
        "name": "Gruvbox light, medium",
        "author": "Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)",
        "variant": "light",
        "background": "#fbf1c7",
        "surface": "#ebdbb2",
        "text": "#504945",
        "accent": "#8f3f71",
        "good": "#79740e"
    },
    {
        "id": "tinted-nord",
        "name": "Nord",
        "author": "arcticicestudio",
        "variant": "dark",
        "background": "#2E3440",
        "surface": "#3B4252",
        "text": "#E5E9F0",
        "accent": "#B48EAD",
        "good": "#A3BE8C"
    },
    {
        "id": "tinted-one-light",
        "name": "One Light",
        "author": "Daniel Pfeifer (http://github.com/purpleKarrot)",
        "variant": "light",
        "background": "#fafafa",
        "surface": "#f0f0f1",
        "text": "#383a42",
        "accent": "#a626a4",
        "good": "#50a14f"
    },
    {
        "id": "tinted-onedark",
        "name": "OneDark",
        "author": "Lalit Magant (http://github.com/tilal6991)",
        "variant": "dark",
        "background": "#282c34",
        "surface": "#353b45",
        "text": "#abb2bf",
        "accent": "#c678dd",
        "good": "#98c379"
    },
    {
        "id": "tinted-rose-pine-dawn",
        "name": "Rosé Pine Dawn",
        "author": "Emilia Dunfelt <edun@dunfelt.se>",
        "variant": "light",
        "background": "#faf4ed",
        "surface": "#fffaf3",
        "text": "#575279",
        "accent": "#ea9d34",
        "good": "#286983"
    },
    {
        "id": "tinted-rose-pine",
        "name": "Rosé Pine",
        "author": "Emilia Dunfelt <edun@dunfelt.se>",
        "variant": "dark",
        "background": "#191724",
        "surface": "#1f1d2e",
        "text": "#e0def4",
        "accent": "#f6c177",
        "good": "#31748f"
    },
    {
        "id": "tinted-solarized-dark",
        "name": "Solarized Dark",
        "author": "Ethan Schoonover (modified by aramisgithub)",
        "variant": "dark",
        "background": "#002b36",
        "surface": "#073642",
        "text": "#93a1a1",
        "accent": "#6c71c4",
        "good": "#859900"
    },
    {
        "id": "tinted-solarized-light",
        "name": "Solarized Light",
        "author": "Ethan Schoonover (modified by aramisgithub)",
        "variant": "light",
        "background": "#fdf6e3",
        "surface": "#eee8d5",
        "text": "#586e75",
        "accent": "#6c71c4",
        "good": "#859900"
    },
    {
        "id": "tinted-tokyo-night-dark",
        "name": "Tokyo Night Dark",
        "author": "Michaël Ball",
        "variant": "dark",
        "background": "#1A1B26",
        "surface": "#16161E",
        "text": "#A9B1D6",
        "accent": "#BB9AF7",
        "good": "#9ECE6A"
    }
];
