"""Rebuild the bundled Qt palette data from our pinned Base16 source files."""

import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read_scheme(path):
    # These vendored files use quoted scalar values. Reject an unfamiliar format
    # instead of silently generating an incomplete palette; this isn't a YAML parser.
    source = path.read_text(encoding="utf-8")
    def field(name):
        match = re.search(r'^\s*' + name + r':\s*"([^"\n]+)"', source, re.MULTILINE)
        if not match:
            raise ValueError(f"Missing quoted {name} in {path}")
        return match.group(1)

    colors = {f"base{i:02X}": field(f"base{i:02X}") for i in range(16)}
    if any(not re.fullmatch(r"#[0-9a-fA-F]{6}", color) for color in colors.values()):
        raise ValueError(f"Invalid color in {path}")
    return {
        "id": "tinted-" + path.stem, "name": field("name"),
        "author": field("author"), "variant": field("variant"),
        "background": colors["base00"], "surface": colors["base01"],
        "text": colors["base05"], "accent": colors["base0E"], "good": colors["base0B"],
    }


themes = [read_scheme(path) for path in sorted((ROOT / "third_party/tinted-schemes/base16").glob("*.yaml"))]
if not themes:
    raise ValueError("No palette source files found")
output = ".pragma library\n\n// Generated by scripts/generate-theme-catalog.py. See third_party/tinted-schemes.\n"
output += "var themes = " + json.dumps(themes, ensure_ascii=False, indent=4) + ";\n"
(ROOT / "src/ui/qt/TintedThemes.js").write_text(output, encoding="utf-8")
print(f"Generated {len(themes)} palettes")
